version: "3.7"
services:
  dev_db:
    image: mongo:4.2.3
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
      MONGO_INITDB_DATABASE: tech
      MONGODB_DATA_DIR: /data/db
      #MONDODB_LOG_DIR: /dev/null
    ports:
      - 27017:27017
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init.js
